# Generated by Django 5.1.7 on 2025-03-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='analysis',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(default=None, max_length=10000),
        ),
    ]
