# Generated by Django 5.1.7 on 2025-03-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_analysis_document_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='analysis',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='summary',
            field=models.TextField(default=None, max_length=10000, null=True),
        ),
    ]
