# Generated by Django 5.1.7 on 2025-03-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_document_analysis_alter_document_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='analysis',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='summary',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
