# Generated by Django 5.1.7 on 2025-03-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alter_document_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='review',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
