# Generated by Django 5.1.7 on 2025-03-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_alter_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
